name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure
      run: cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build
      run: cmake --build build -- -j$(nproc)
